// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZpl0MDoKNGAIsY6XLun7bNrDQ9hG94yA',
    appId: '1:684537233683:web:6acc21af499c81e2949ae6',
    messagingSenderId: '684537233683',
    projectId: 'sanitary-mart-d87f5',
    authDomain: 'sanitary-mart-d87f5.firebaseapp.com',
    storageBucket: 'sanitary-mart-d87f5.appspot.com',
    measurementId: 'G-47BYRKMEEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCouwrdZim8l0Sd_CqBc-UDcZGiFKWZKSU',
    appId: '1:684537233683:android:b24237040e4cf63f949ae6',
    messagingSenderId: '684537233683',
    projectId: 'sanitary-mart-d87f5',
    storageBucket: 'sanitary-mart-d87f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1TDSYimP4_rJb94PabzazCDd0niLdVqc',
    appId: '1:684537233683:ios:84e4c6e301e78349949ae6',
    messagingSenderId: '684537233683',
    projectId: 'sanitary-mart-d87f5',
    storageBucket: 'sanitary-mart-d87f5.appspot.com',
    androidClientId: '684537233683-0tbqshk7fnsl90bko19pndivnr4fa6m1.apps.googleusercontent.com',
    iosClientId: '684537233683-bld203nkqcdc14v3i6bro9onieuqhm6g.apps.googleusercontent.com',
    iosBundleId: 'com.codexia.sanitaryMartAdmin',
  );
}
